actions16

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -43,25 +43,40 @@ jobs:
           yarn serve > serve.log 2>&1 &
           echo $! > serve.pid
 
-      - name: Install Puppeteer Dependencies
+#      - name: Install Puppeteer Dependencies
+#        run: |
+#          sudo apt-get update
+#          sudo apt-get install -y \
+#            gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
+#            libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
+#            libgdk-pixbuf2.0-0 libglib2.0-0 libnspr4 libnss3 \
+#            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-xcb1 \
+#            libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
+#            libxi6 libxrandr2 libxrender1 libxtst6 ca-certificates \
+#            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
+#
+#      # Шаг 3. Очистка кэша Puppeteer
+#      - name: Clear Puppeteer Cache
+#        run: rm -rf ~/.cache/puppeteer
+#
+#      # Шаг 4. Установка Puppeteer и его браузера
+#      - name: Install Puppeteer Browser
+#        run: npx puppeteer install
+
+      - name: Check Puppeteer Browser
         run: |
-          sudo apt-get update
-          sudo apt-get install -y \
-            gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
-            libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 \
-            libgdk-pixbuf2.0-0 libglib2.0-0 libnspr4 libnss3 \
-            libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-xcb1 \
-            libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
-            libxi6 libxrandr2 libxrender1 libxtst6 ca-certificates \
-            fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
+          if [ -f ~/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome ]; then
+            echo "Browser exists!"
+          else
+            echo "Browser not found!"
+            exit 1
+          fi
 
-      # Шаг 3. Очистка кэша Puppeteer
-      - name: Clear Puppeteer Cache
-        run: rm -rf ~/.cache/puppeteer
-
-      # Шаг 4. Установка Puppeteer и его браузера
-      - name: Install Puppeteer Browser
-        run: npx puppeteer install
+      - name: Check
+        run: |
+          echo $PUPPETEER_CACHE_DIR
+          ls -l ~/.cache/puppeteer
+          ls -l ~/.cache/puppeteer/chrome/linux-121.0.6167.85/chrome-linux64/chrome
 
       - name: Generate PDF
         run: yarn generate:pdf
